## Import Libraries

In [55]:
import torch
import random
from collections import OrderedDict
import torchvision
import numpy as np
import math

## Generate Randomized Inputs

In [56]:
# Generate inputs
torch.manual_seed(4)
pixel_input = torch.randn(1,3,32,32)
pixel_input

tensor([[[[-0.9414,  1.2632, -0.1838,  ...,  0.8488, -0.6776, -0.9445],
          [-0.4815,  1.2434,  2.3693,  ..., -0.1941,  0.0048, -1.3165],
          [ 0.0204, -0.1652,  0.2109,  ..., -1.0060, -0.6573,  1.5234],
          ...,
          [ 0.7384,  1.3529, -1.1076,  ...,  0.0411,  1.0224, -0.5645],
          [ 0.3890, -1.2504,  1.0175,  ...,  0.2299, -1.1533, -0.7816],
          [ 0.3808, -2.0276, -0.8032,  ...,  0.1094, -0.5286,  1.1171]],

         [[-1.5659, -0.8505,  0.8251,  ...,  0.5010,  1.6078, -1.3481],
          [-0.6769,  0.3689,  0.1058,  ...,  0.3293, -0.3494,  1.2767],
          [ 0.6511, -0.5911, -0.6523,  ...,  0.0262, -1.3822, -0.7295],
          ...,
          [-0.6567,  0.1056,  0.8520,  ..., -0.6127,  0.2219,  0.3437],
          [ 1.3538, -0.7093, -0.5943,  ..., -0.7441, -1.5384,  1.3397],
          [ 0.5674,  0.8825,  0.4475,  ...,  0.0167,  1.6057,  0.4327]],

         [[ 0.9296, -0.0498,  2.0177,  ...,  0.0307, -1.0810, -0.4701],
          [ 1.5071, -0.0180,  

## Model 1

In [70]:
m1 = torch.nn.MaxPool2d(kernel_size=2, stride=1, padding=0,
                        dilation=1, return_indices=False, ceil_mode=False)
torch_out = m1(pixel_input)
torch_out

tensor([[[[ 1.2632,  2.3693,  2.3693,  ...,  1.3940,  0.8488,  0.0048],
          [ 1.2434,  2.3693,  2.3693,  ...,  1.3940,  0.0048,  1.5234],
          [ 0.0366,  2.8345,  2.8345,  ...,  0.6718,  0.6718,  1.5234],
          ...,
          [ 1.3529,  1.3529,  1.0262,  ...,  1.5966,  1.0224,  1.0224],
          [ 1.3529,  1.3529,  1.0262,  ...,  1.5966,  1.0224,  1.0224],
          [ 0.3890,  1.0175,  1.0175,  ...,  1.2254,  0.2299,  1.1171]],

         [[ 0.3689,  0.8251,  0.8251,  ...,  0.5010,  1.6078,  1.6078],
          [ 0.6511,  0.3689,  0.4504,  ...,  0.3898,  0.3293,  1.2767],
          [ 0.6511, -0.4763,  0.1878,  ...,  0.8177,  0.6531,  0.6531],
          ...,
          [ 0.8639,  0.8520,  0.8520,  ..., -0.6127,  1.2985,  2.6637],
          [ 1.3538,  0.8520,  0.8520,  ...,  0.2692,  0.2219,  1.3397],
          [ 1.3538,  0.8825,  0.4475,  ...,  0.2692,  1.6057,  1.6057]],

         [[ 1.5071,  2.0177,  2.0177,  ...,  0.0307,  0.9706,  0.9706],
          [ 1.5071,  0.5933,  

In [31]:
def model1(x):
    result = []
    for k in range(3): 
        img = np.zeros((31,31))
        for i in range(31):
            for j in range(31):
                temp = np.max(x[0][k][i:i+2,j:j+2])
                img[i][j] = temp
        result.append(img)
    return result

In [34]:
my_out = model1(np.array(pixel_input))
my_out

[array([[ 1.26324677,  2.36933231,  2.36933231,  0.28294411,  1.68924356,
          1.68924356,  0.62445748,  0.62445748, -0.20505528,  0.39756078,
          0.66992599,  0.82012343,  0.82012343,  0.04669524,  1.40717816,
          1.51909697,  2.7204206 ,  2.7204206 ,  0.98714769,  1.13961565,
          1.13961565,  1.18773258,  1.18773258,  0.76773548, -0.18534321,
         -0.18534321, -0.2346396 ,  1.39395213,  1.39395213,  0.84883648,
          0.00481835],
        [ 1.24344778,  2.36933231,  2.36933231,  0.51671112,  1.68924356,
          1.68924356,  0.29732424,  1.27097952,  1.81166446,  1.81166446,
          1.53196073,  0.82012343,  0.82012343,  1.05328035,  1.40717816,
          1.40717816,  2.7204206 ,  2.7204206 ,  0.98714769,  1.08605182,
          1.08605182,  1.72279191,  1.72279191,  1.09151113,  1.09151113,
          0.45500222, -0.24286361,  1.39395213,  1.39395213,  0.00481835,
          1.52339709],
        [ 0.03657929,  2.83451843,  2.83451843,  0.51671112,  0.24

## Model 2

In [71]:
m2 = torch.nn.AvgPool2d(kernel_size=2, stride=1, padding=0, ceil_mode=False, 
                        count_include_pad=True, divisor_override=None)
torch_out = m2(pixel_input)
torch_out

tensor([[[[ 2.7093e-01,  1.1731e+00,  6.5475e-01,  ...,  4.0680e-01,
           -4.4949e-03, -7.3344e-01],
          [ 1.5428e-01,  9.1463e-01,  8.4498e-01,  ..., -2.1992e-01,
           -4.6312e-01, -1.1139e-01],
          [-3.7360e-01,  3.7351e-01,  8.4678e-01,  ..., -6.5268e-01,
           -1.6983e-01, -1.0927e-01],
          ...,
          [ 1.6302e-01, -2.2092e-01, -4.0282e-01,  ...,  5.3670e-01,
           -1.1023e-01, -4.0926e-01],
          [ 3.0746e-01,  3.0849e-03,  7.5808e-02,  ...,  3.1631e-01,
            3.5019e-02, -3.6927e-01],
          [-6.2706e-01, -7.6594e-01,  1.2568e-01,  ...,  2.4059e-01,
           -3.3565e-01, -3.3662e-01]],

         [[-6.8111e-01,  1.1233e-01,  3.2166e-01,  ..., -1.1544e-01,
            5.2216e-01,  2.9676e-01],
          [-6.2006e-02, -1.9216e-01, -1.4788e-01,  ...,  1.9534e-01,
           -3.4405e-01, -2.9610e-01],
          [-2.1070e-01, -5.8617e-01, -3.5905e-01,  ...,  3.6448e-01,
           -1.1966e-01, -3.0143e-01],
          ...,
     

In [36]:
def model2(x):
    result = []
    for k in range(3): 
        img = np.zeros((31,31))
        for i in range(31):
            for j in range(31):
                temp = np.mean(x[0][k][i:i+2,j:j+2])
                img[i][j] = temp
        result.append(img)
    return result

In [37]:
my_out = model2(np.array(pixel_input))
my_out

[array([[ 2.70934790e-01,  1.17306435e+00,  6.54753149e-01,
          7.66030699e-02,  3.21043491e-01, -2.29821190e-01,
         -4.60645884e-01, -2.68809259e-01, -7.71697521e-01,
         -5.23866534e-01,  1.84588611e-01,  5.19149065e-01,
         -2.54997313e-02, -1.19481552e+00, -1.15603209e+00,
          1.94874778e-01,  8.86250734e-01,  3.64940107e-01,
          6.02844507e-02,  7.64816880e-01,  5.14115214e-01,
          2.65046775e-01,  6.68848515e-01, -5.19965589e-02,
         -7.13417649e-01, -5.74584723e-01, -7.26504803e-01,
         -2.08735406e-01,  4.06800151e-01, -4.49491618e-03,
         -7.33442545e-01],
        [ 1.54279470e-01,  9.14628923e-01,  8.44978809e-01,
          2.02025741e-01,  3.36362451e-01,  2.10571349e-01,
         -8.34843516e-02,  1.84243053e-01,  2.67318010e-01,
          2.63913423e-01,  2.35654801e-01,  9.76955891e-03,
         -6.23523414e-01, -8.10894966e-01,  1.29233152e-01,
          6.00426912e-01,  1.50778115e+00,  9.21900153e-01,
         -1.4

## Model 3

In [72]:
m3 = torch.nn.Conv2d(in_channels=3, out_channels=6,kernel_size=3, stride=1, 
                     padding=0, dilation=1, groups=1, bias=True, padding_mode='zeros')

m3.weight.data.fill_(0.01)
m3.bias.data.fill_(0.02)
torch_out = m3(pixel_input)
torch_out

tensor([[[[ 0.0668,  0.0671,  0.0674,  ..., -0.0188, -0.0397, -0.0331],
          [ 0.0564,  0.0274,  0.0592,  ...,  0.0147,  0.0073, -0.0015],
          [ 0.0047, -0.0619, -0.0102,  ...,  0.0302,  0.0137,  0.0014],
          ...,
          [-0.0241,  0.0142, -0.0195,  ..., -0.0342, -0.0397, -0.0250],
          [ 0.0145,  0.0100,  0.0447,  ..., -0.0266, -0.0427, -0.0341],
          [ 0.0747,  0.0399,  0.0579,  ..., -0.0348, -0.0016,  0.0171]],

         [[ 0.0668,  0.0671,  0.0674,  ..., -0.0188, -0.0397, -0.0331],
          [ 0.0564,  0.0274,  0.0592,  ...,  0.0147,  0.0073, -0.0015],
          [ 0.0047, -0.0619, -0.0102,  ...,  0.0302,  0.0137,  0.0014],
          ...,
          [-0.0241,  0.0142, -0.0195,  ..., -0.0342, -0.0397, -0.0250],
          [ 0.0145,  0.0100,  0.0447,  ..., -0.0266, -0.0427, -0.0341],
          [ 0.0747,  0.0399,  0.0579,  ..., -0.0348, -0.0016,  0.0171]],

         [[ 0.0668,  0.0671,  0.0674,  ..., -0.0188, -0.0397, -0.0331],
          [ 0.0564,  0.0274,  

In [39]:
def model3(x,w,b):
    result = []
    for k in range(6): 
        img = np.zeros((30,30))
        for i in range(30):
            for j in range(30):
                temp = []
                for g in range(3):
                    temp.append(x[0][g][i:i+3,j:j+3] * w)
                    img[i][j] = np.sum(temp) + b
        result.append(img)
    return result

In [40]:
my_out = model3(np.array(pixel_input),0.01,0.02)
my_out

[array([[ 6.67929468e-02,  6.70646098e-02,  6.73803096e-02,
          7.49999103e-02,  1.64443911e-02,  2.55263583e-02,
         -3.17565385e-02,  3.28900781e-02,  2.14549037e-02,
         -1.46855894e-02, -2.84081656e-02, -6.19202438e-02,
         -5.60383978e-02, -5.94760510e-02,  3.95125568e-03,
          7.38544320e-02,  4.24690400e-02,  2.39468664e-02,
          4.52934064e-03,  2.97812861e-02,  1.94473014e-02,
          2.73398584e-02,  7.33248633e-02,  6.52276953e-02,
          4.61675175e-02,  1.48951835e-02, -1.23942006e-02,
         -1.87567505e-02, -3.97223341e-02, -3.30631952e-02],
        [ 5.64224985e-02,  2.73632002e-02,  5.91854607e-02,
          9.00078905e-02,  3.82512961e-02,  6.05460186e-02,
          7.70062905e-03,  2.57429685e-02, -1.07461169e-03,
         -4.23647757e-02, -3.63522652e-02, -9.12786457e-02,
         -1.06005217e-01, -5.14133605e-02,  2.62974487e-02,
          1.30793330e-01,  7.92584386e-02,  3.55552709e-02,
         -3.30674085e-02, -1.17900442e-

## Model 4

In [73]:
m4 = torch.nn.Conv2d(in_channels=3, out_channels=6, kernel_size=5, stride=2, 
                     padding=0, dilation=2, groups=1, bias=True, padding_mode='zeros')

m4.weight.data.fill_(0.01)
m4.bias.data.fill_(0.02)
torch_out = m4(pixel_input)
torch_out

tensor([[[[-0.0058, -0.0492, -0.0396, -0.0859,  0.0429,  0.0389,  0.0579,
            0.0867,  0.0708,  0.0365,  0.0559, -0.0233],
          [-0.0602, -0.1315, -0.1156, -0.1419, -0.0038,  0.0003,  0.0450,
            0.0975,  0.1105,  0.0433,  0.0574, -0.0373],
          [-0.0651, -0.1520, -0.0758, -0.0897,  0.0054,  0.0629,  0.1020,
            0.1253,  0.1260,  0.0743,  0.0843,  0.0276],
          [-0.0153, -0.1313, -0.0581, -0.1165, -0.0477, -0.0334,  0.0227,
            0.0513,  0.0739,  0.0173,  0.0331, -0.0541],
          [ 0.0139, -0.0881, -0.0498, -0.1119, -0.0549, -0.0301,  0.0339,
            0.1019,  0.1548,  0.1161,  0.1245,  0.0076],
          [-0.0712, -0.1495, -0.1154, -0.1401, -0.1069, -0.1046, -0.0308,
            0.0540,  0.1615,  0.1305,  0.1549,  0.0107],
          [ 0.0458, -0.0034,  0.0390, -0.0255,  0.0062, -0.0085,  0.0027,
            0.1029,  0.1295,  0.1088,  0.1391,  0.0422],
          [-0.0239, -0.0446,  0.0183, -0.0671, -0.0435, -0.0295,  0.0204,
         

In [42]:
def model4(x,w,b):
    result = []
    for k in range(6): 
        img = np.zeros((12,12))
        for i in range(0,24,2):
            for j in range(0,24,2):
                temp = []
                for g in range(3):
                    temp.append(x[0][g][i:i+9,j:j+9] * w)
                    img[i//2][j//2] = np.sum(temp) + b
        result.append(img)
    return result

In [43]:
w = np.zeros((9,9))
for i in range(0,9,2):
    for j in range(0,9,2):
        w[i][j] = 0.01
my_out = model4(np.array(pixel_input),w,0.02)
my_out

[array([[-0.00583622, -0.04918382, -0.03957952, -0.08587536,  0.04287978,
          0.03888594,  0.05793309,  0.08667062,  0.07078781,  0.03645271,
          0.05588553, -0.0232997 ],
        [-0.0602257 , -0.13145887, -0.11560543, -0.14191002, -0.00381423,
          0.00030951,  0.04502451,  0.09752336,  0.11047711,  0.04332922,
          0.05737733, -0.03731946],
        [-0.06513038, -0.15204307, -0.07584157, -0.08968028,  0.00542701,
          0.06289101,  0.10200724,  0.12532612,  0.12599421,  0.07425594,
          0.08432632,  0.02761104],
        [-0.01529851, -0.13130492, -0.05809676, -0.11648442, -0.04765138,
         -0.03335347,  0.02266593,  0.05125236,  0.07389364,  0.01733974,
          0.03309645, -0.05410252],
        [ 0.0139462 , -0.08814935, -0.04980789, -0.11188318, -0.05487575,
         -0.03010628,  0.03389649,  0.1018656 ,  0.15478555,  0.11614191,
          0.12447648,  0.00760006],
        [-0.07121199, -0.14946036, -0.11543669, -0.14005577, -0.10687864,
      

## Model 5

In [69]:
m5 = torch.nn.ConvTranspose2d(in_channels=3, out_channels=4, kernel_size=3, stride=1, padding=0, 
                              output_padding=0, groups=1, bias=True, dilation=1, padding_mode='zeros')

m5.weight.data.fill_(0.01)
m5.bias.data.fill_(0.02)
torch_out = m5(pixel_input)
torch_out

tensor([[[[ 0.0042,  0.0079,  0.0344,  ...,  0.0047, -0.0091, -0.0076],
          [ 0.0077,  0.0273,  0.0797,  ...,  0.0008, -0.0082, -0.0130],
          [ 0.0122,  0.0129,  0.0668,  ..., -0.0331, -0.0400, -0.0090],
          ...,
          [ 0.0674,  0.0759,  0.0747,  ...,  0.0171,  0.0217,  0.0240],
          [ 0.0664,  0.0605,  0.0686,  ...,  0.0242,  0.0387,  0.0421],
          [ 0.0330,  0.0509,  0.0487,  ...,  0.0582,  0.0634,  0.0398]],

         [[ 0.0042,  0.0079,  0.0344,  ...,  0.0047, -0.0091, -0.0076],
          [ 0.0077,  0.0273,  0.0797,  ...,  0.0008, -0.0082, -0.0130],
          [ 0.0122,  0.0129,  0.0668,  ..., -0.0331, -0.0400, -0.0090],
          ...,
          [ 0.0674,  0.0759,  0.0747,  ...,  0.0171,  0.0217,  0.0240],
          [ 0.0664,  0.0605,  0.0686,  ...,  0.0242,  0.0387,  0.0421],
          [ 0.0330,  0.0509,  0.0487,  ...,  0.0582,  0.0634,  0.0398]],

         [[ 0.0042,  0.0079,  0.0344,  ...,  0.0047, -0.0091, -0.0076],
          [ 0.0077,  0.0273,  

In [45]:
def model5(x,w,b):
    result = []
    for k in range(4): 
        img = np.zeros((34,34))
        for i in range(34):
            for j in range(34):
                temp = []
                for g in range(3):
                    temp.append(x[g][i:i+3,j:j+3] * w)
                    img[i][j] = np.sum(temp) + b
        result.append(img)
    return result

In [47]:
pixel_inputT = []
for k in range(3):
    tempT= np.zeros((36,36))  
    for i in range(2,34):
        for j in range(2,34):
            tempT[i][j] = np.array(pixel_input)[0][k][i - 2][j - 2]
    pixel_inputT.append(tempT)
my_out = model5(np.array(pixel_inputT),0.01,0.02)
my_out

[array([[ 0.00422237,  0.00785206,  0.03444252, ...,  0.00466986,
         -0.00913514, -0.0076273 ],
        [ 0.0077093 ,  0.02728192,  0.07967576, ...,  0.00082786,
         -0.00821772, -0.01297009],
        [ 0.01221586,  0.01287992,  0.06679295, ..., -0.0330632 ,
         -0.04000976, -0.0090418 ],
        ...,
        [ 0.06737474,  0.07587093,  0.07467946, ...,  0.01706105,
          0.02167309,  0.02403409],
        [ 0.06635028,  0.06052052,  0.06864663, ...,  0.02416   ,
          0.03873218,  0.04206383],
        [ 0.03298629,  0.050866  ,  0.0487241 , ...,  0.05821509,
          0.06344718,  0.03981862]]),
 array([[ 0.00422237,  0.00785206,  0.03444252, ...,  0.00466986,
         -0.00913514, -0.0076273 ],
        [ 0.0077093 ,  0.02728192,  0.07967576, ...,  0.00082786,
         -0.00821772, -0.01297009],
        [ 0.01221586,  0.01287992,  0.06679295, ..., -0.0330632 ,
         -0.04000976, -0.0090418 ],
        ...,
        [ 0.06737474,  0.07587093,  0.07467946, ...,  

## Model 6

In [65]:
torch_out = torch.flatten(pixel_input, start_dim=0, end_dim=-1)
torch_out

tensor([-0.9414,  1.2632, -0.1838,  ..., -0.6494,  1.2858,  0.4321])

In [66]:
def model6(x):
    result = []
    for k in range(3):
        for i in range(32):
            for j in range(32):
                result.append(x[0][k][i][j])
    return result
my_out = model6(np.array(pixel_input))
my_out

[-0.9414165,
 1.2632468,
 -0.18376939,
 0.15050545,
 0.10750223,
 -0.27803233,
 -2.6021352,
 0.6244575,
 -0.8683629,
 -0.20505528,
 0.39756078,
 0.669926,
 -0.05370698,
 0.046695244,
 -1.7671137,
 -2.1204596,
 1.519097,
 -0.66819805,
 0.0030777093,
 -0.15354781,
 1.1396157,
 -0.23018745,
 1.1877326,
 0.7677355,
 -0.7588325,
 -0.1853432,
 -0.855791,
 -0.2346396,
 -0.42152935,
 0.8488365,
 -0.6775759,
 -0.9445412,
 -0.4815389,
 1.2434478,
 2.3693323,
 0.2829441,
 -0.23453952,
 1.6892436,
 0.27163917,
 -0.13654506,
 -0.6947865,
 -1.3185855,
 -0.96938604,
 0.6402537,
 0.82012343,
 -0.91511065,
 -2.143733,
 1.4071782,
 -0.026316443,
 2.7204206,
 -0.5955398,
 0.9871477,
 1.0860518,
 0.060980845,
 0.041661195,
 0.6782648,
 -0.895154,
 -1.014341,
 -0.24286361,
 -1.5727249,
 1.3939521,
 -0.19405861,
 0.004818352,
 -1.3164716,
 0.020401197,
 -0.16519219,
 0.21092775,
 0.5167111,
 0.24298728,
 -0.35224152,
 -0.76635575,
 0.29732424,
 1.2709795,
 1.8116645,
 1.5319607,
 -0.26020923,
 -1.1610898,
 

## Model 7

In [67]:
torch_out = torch.sigmoid(pixel_input,out=None)
torch_out

tensor([[[[0.2806, 0.7796, 0.4542,  ..., 0.7003, 0.3368, 0.2800],
          [0.3819, 0.7762, 0.9145,  ..., 0.4516, 0.5012, 0.2114],
          [0.5051, 0.4588, 0.5525,  ..., 0.2678, 0.3413, 0.8210],
          ...,
          [0.6766, 0.7946, 0.2483,  ..., 0.5103, 0.7354, 0.3625],
          [0.5960, 0.2226, 0.7345,  ..., 0.5572, 0.2399, 0.3140],
          [0.5941, 0.1163, 0.3093,  ..., 0.5273, 0.3708, 0.7535]],

         [[0.1728, 0.2993, 0.6953,  ..., 0.6227, 0.8331, 0.2062],
          [0.3370, 0.5912, 0.5264,  ..., 0.5816, 0.4135, 0.7819],
          [0.6572, 0.3564, 0.3425,  ..., 0.5065, 0.2007, 0.3253],
          ...,
          [0.3415, 0.5264, 0.7010,  ..., 0.3514, 0.5552, 0.5851],
          [0.7948, 0.3298, 0.3556,  ..., 0.3221, 0.1768, 0.7924],
          [0.6382, 0.7073, 0.6100,  ..., 0.5042, 0.8328, 0.6065]],

         [[0.7170, 0.4876, 0.8826,  ..., 0.5077, 0.2533, 0.3846],
          [0.8186, 0.4955, 0.5263,  ..., 0.3518, 0.7252, 0.3788],
          [0.4450, 0.2433, 0.6441,  ..., 0

In [68]:
def model7(x):
    def sigmoid(x):
        return 1 / (1 + math. exp(-x))
    result = []
    for k in range(3):
        temp = np.zeros((32,32))
        for i in range(32):
            for j in range(32):
                temp[i][j] = sigmoid(x[0][k][i][j])
        result.append(temp)
    return result
my_out = model7(np.array(pixel_input))
my_out

[array([[0.2806143 , 0.77958452, 0.45418651, ..., 0.70032301, 0.33680255,
         0.27998395],
        [0.3818888 , 0.77616358, 0.91445865, ..., 0.45163703, 0.50120459,
         0.21140593],
        [0.50510012, 0.45879561, 0.5525373 , ..., 0.2677703 , 0.34134843,
         0.82103817],
        ...,
        [0.67664123, 0.79459626, 0.24831947, ..., 0.51028211, 0.73543737,
         0.36250755],
        [0.59603456, 0.22263481, 0.73447668, ..., 0.55722397, 0.23987812,
         0.31396691],
        [0.5940651 , 0.11633132, 0.30934177, ..., 0.52733497, 0.37084045,
         0.75345631]]),
 array([[0.17279944, 0.29933182, 0.69531942, ..., 0.62269257, 0.83310806,
         0.20618668],
        [0.33695144, 0.59118944, 0.52642798, ..., 0.58158226, 0.41351919,
         0.78189309],
        [0.65724902, 0.356392  , 0.34247985, ..., 0.50654306, 0.20065246,
         0.32530642],
        ...,
        [0.34149217, 0.52638464, 0.70098267, ..., 0.35143316, 0.55523832,
         0.58509623],
        [0.7

## Model 8

In [57]:
rois_in_feature = torch.Tensor([[0, 4.125, 5.464, 13.93, 20.47]]) 
roi_start_w = 4
roi_start_h = 5
roi_end_w = 13
roi_end_h = 20

roi_width = (roi_end_w - roi_start_w + 1)
roi_height = (roi_end_h - roi_start_h + 1)

bin_size_w = roi_width / 3
bin_size_h = roi_height / 3
torch_out = torchvision.ops.roi_pool(pixel_input, rois_in_feature,output_size=(3, 3))
torch_out

tensor([[[[1.8144, 1.6986, 1.5493],
          [1.9597, 1.4444, 2.1448],
          [1.0979, 2.7135, 1.1213]],

         [[3.5865, 1.7785, 1.9873],
          [1.8513, 1.8513, 1.0914],
          [1.7524, 1.7525, 1.2282]],

         [[1.7486, 2.2146, 1.3215],
          [2.4261, 2.4261, 2.2680],
          [2.4261, 2.4261, 1.8381]]]])

In [60]:
my_out = []
for j in range(3):
    result = []
    for i in range(3):
        result.append(pixel_input[..., int(6+bin_size_h*(j)):math.ceil(6+bin_size_h*(j+1)), int(5+bin_size_w*(i)):math.ceil(5+bin_size_w*(i+1))][0][0].max())
    my_out.append(result)
my_out

[[tensor(1.8144), tensor(1.4444), tensor(1.5493)],
 [tensor(1.9597), tensor(1.4444), tensor(2.1448)],
 [tensor(0.9330), tensor(2.7135), tensor(1.1213)]]

## Model 9

In [62]:
running_mean = torch.zeros(3) + 1
running_var = torch.ones(3) * 2
torch_out = torch.nn.functional.batch_norm(pixel_input, running_mean, running_var, weight=None, 
                                           bias=None, training=False, momentum=0.1, eps=1e-05)
torch_out

tensor([[[[-1.3728,  0.1861, -0.8370,  ..., -0.1069, -1.1862, -1.3750],
          [-1.0476,  0.1721,  0.9683,  ..., -0.8443, -0.7037, -1.6380],
          [-0.6927, -0.8239, -0.5580,  ..., -1.4184, -1.1719,  0.3701],
          ...,
          [-0.1850,  0.2495, -1.4903,  ..., -0.6780,  0.0158, -1.1063],
          [-0.4321, -1.5913,  0.0123,  ..., -0.5445, -1.5226, -1.2598],
          [-0.4378, -2.1409, -1.2751,  ..., -0.6297, -1.0809,  0.0828]],

         [[-1.8144, -1.3085, -0.1237,  ..., -0.3529,  0.4298, -1.6603],
          [-1.1858, -0.4463, -0.6323,  ..., -0.4743, -0.9542,  0.1957],
          [-0.2467, -1.1250, -1.1683,  ..., -0.6886, -1.6845, -1.2229],
          ...,
          [-1.1714, -0.6324, -0.1047,  ..., -1.1404, -0.5502, -0.4641],
          [ 0.2502, -1.2086, -1.1274,  ..., -1.2333, -1.7949,  0.2402],
          [-0.3059, -0.0831, -0.3907,  ..., -0.6953,  0.4283, -0.4012]],

         [[-0.0498, -0.7423,  0.7196,  ..., -0.6854, -1.4715, -1.0395],
          [ 0.3586, -0.7199, -

In [63]:
def model9(x,mean,var,eps):
    result = []
    for k in range(3):
        img = np.zeros((32,32))
        for i in range(32):
            for j in range(32):
                img[i][j] = (x[0][k][i][j] - mean)/ np.sqrt(var + eps)
        result.append(img)
    return result

In [64]:
my_out = model9(np.array(pixel_input),1,2,1e-05)
my_out

[array([[-1.37278534,  0.18614311, -0.83704927, ..., -0.10688848,
         -1.18622232, -1.37499484],
        [-1.04760358,  0.17214315,  0.96826174, ..., -0.84432483,
         -0.70369793, -1.63798867],
        [-0.69267923, -0.82391324, -0.55795694, ..., -1.41842774,
         -1.17187873,  0.3700967 ],
        ...,
        [-0.18499369,  0.2495067 , -1.49029122, ..., -0.67801878,
          0.01583023, -1.10626375],
        [-0.43206285, -1.59125315,  0.01234293, ..., -0.54453931,
         -1.52264306, -1.25980535],
        [-0.43784218, -2.14085933, -1.27505063, ..., -0.62971308,
         -1.0808899 ,  0.0828245 ]]),
 array([[-1.81437177, -1.30848488, -0.12366744, ..., -0.35285064,
          0.42979032, -1.66032947],
        [-1.18575103, -0.44626483, -0.63228586, ..., -0.47427505,
         -0.95419297,  0.19567907],
        [-0.24673808, -1.12504552, -1.16832315, ..., -0.68859743,
         -1.68448074, -1.2229318 ],
        ...,
        [-1.17142671, -0.63240878, -0.10466452, ..., -

## Model 10

In [9]:
# Generate inputs
torch.manual_seed(4)
pixel_input = torch.FloatTensor(1,32).uniform_(0,1)
target = torch.randint(32, (1,))

torch_out = torch.nn.functional.cross_entropy(pixel_input, target, weight=None, size_average=None, 
                                              ignore_index=-100, reduce=None, reduction='mean')
torch_out

tensor(3.0638)

In [10]:
def model10(x,target):
    temp = 0
    for i in range(32):
        temp += np.exp(x[0][i])    
    result = -1 * x[0][target[0]] + np.log(temp)
    return result

In [13]:
my_out = model10(np.array(pixel_input),np.array(target))
round(my_out,4)

3.0638

## Model 11

In [25]:
# Generate inputs
torch.manual_seed(4)
pixel_input = torch.randn(1,3,32,32)
target = torch.randn(1,3,32,32)

torch_out = torch.nn.functional.mse_loss(pixel_input, target, size_average=None, 
                                   reduce=None, reduction='mean')
torch_out

tensor(1.9994)

In [26]:
def model11(x,target):
    result = []
    for k in range(3):
        for i in range(32):
              for j in range(32):
                    result.append(np.square(x[0][k][i][j] - target[0][k][i][j]))
    return np.mean(result)

In [27]:
my_out = model11(np.array(pixel_input),np.array(target))
round(my_out,4)

1.9994